/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_wstt_gt_api_utils_MemFillTool */

#ifndef _Included_com_tencent_wstt_gt_api_utils_MemFillTool
#define _Included_com_tencent_wstt_gt_api_utils_MemFillTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_wstt_gt_api_utils_MemFillTool
 * Method:    fillMem
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_tencent_wstt_gt_api_utils_MemFillTool_fillMem
  (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_com_tencent_wstt_gt_api_utils_MemFillTool_freeMem
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
